// Code generated by wasm2go. DO NOT EDIT.

package parser

import "encoding/binary"

type Module struct {
	Memory           []byte
	___stack_pointer int32
	_env             Ienv
}

func New(v0 Ienv) *Module {
	m := &Module{}
	m._env = v0
	m.Memory = make([]byte, 131072)
	m.___stack_pointer = i32_const(65536)
	copy(m.Memory[65536:], data0)
	copy(m.Memory[65950:], data1)
	return m
}

type Ienv interface {
	Istrlen(m *Module, v0 int32) int32
	Itolower(m *Module, v0 int32) int32
}

func (m Module) _strlen(v0 int32) int32 {
	return m._env.Istrlen(&m, v0)
}
func (m Module) _tolower(v0 int32) int32 {
	return m._env.Itolower(&m, v0)
}
func (m Module) _malloc(v0 int32) int32 {
	var v1, v2, v3 int32
	_, _, _ = v1, v2, v3
	{
		if v0 == 0 {
			goto l0
		}
		t2 := v0
		t3 := t2 + i32_const(15)
		t4 := t3 & i32_const(-16)
		v0 = t4
		t5 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(i32_const(65948)):]))
		v3 = t5
		t6 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(i32_const(65952)):]))
		v2 = t6
		t7 := t5 - t6
		v1 = t7
		if uint32(t4) > uint32(t7) {
			t9 := v0
			t11 := t9 - v1
			t12 := t11 + i32_const(65535)
			v1 = t12
			t14 := memory_grow(&m.Memory, i32_shr_u(t12, i32_const(16)))
			if t14 == i32_const(-1) {
				goto l0
			}
			t16 := v3
			t17 := v1
			binary.LittleEndian.PutUint32(m.Memory[uint32(i32_const(65948)):], uint32(t16+t17&i32_const(-65536)))
		}
		t20 := v0
		binary.LittleEndian.PutUint32(m.Memory[uint32(i32_const(65952)):], uint32(t20+v2))
		t23 := v2
		return t23
	}
l0:
	;
	return i32_const(0)
}
func (m Module) Xsql3parse_table(v0 int32, v1 int32, v2 int32) int32 {
	var v3, v4, v5, v6, v7, v8, v9, v10, v11 int32
	_, _, _, _, _, _, _, _, _ = v3, v4, v5, v6, v7, v8, v9, v10, v11
	t0 := m.___stack_pointer
	t1 := t0 + i32_const(-64)
	v3 = t1
	m.___stack_pointer = t1
	{
		if v0 == 0 {
			goto l0
		}
		if v1 == 0 {
			t7 := m._strlen(v0)
			v1 = t7
		}
		t8 := v2
		if t8 != 0 {
			t9 := v2
			binary.LittleEndian.PutUint32(m.Memory[uint32(t9):], uint32(i32_const(0)))
		}
		if v1 == 0 {
			goto l0
		}
		{
			{
				var t12 int32
				{
					{
						t13 := m._malloc(i32_const(64))
						v8 = t13
						if t13 != 0 {
							t14 := v3
							t15 := t14 + i32_const(28)
							binary.LittleEndian.PutUint32(m.Memory[uint32(t15):], uint32(i32_const(0)))
							t16 := v3
							binary.LittleEndian.PutUint64(m.Memory[uint32(t16+20):], uint64(i64_const(0)))
							t17 := v3
							binary.LittleEndian.PutUint32(m.Memory[uint32(t17+16):], uint32(v1))
							t19 := v3
							binary.LittleEndian.PutUint32(m.Memory[uint32(t19+12):], uint32(v0))
							t21 := v3
							binary.LittleEndian.PutUint32(m.Memory[uint32(t21+36):], uint32(v8))
							t23 := v3
							t24 := v8
							binary.LittleEndian.PutUint32(m.Memory[uint32(t23+32):], uint32(t24+i32_const(16)))
							v1 = i32_const(3)
							t26 := v3
							t27 := t26 + i32_const(12)
							v0 = t27
							t28 := m._sql3lexer_next(t27)
							v4 = t28
							if t28 != i32_const(57) {
								t30 := v4
								if t30 != i32_const(6) {
									goto l1
								}
								t33 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v3+36):]))
								v4 = t33
								binary.LittleEndian.PutUint32(m.Memory[uint32(t33+44):], uint32(i32_const(1)))
								t35 := m._sql3lexer_next(v0)
								v5 = t35
								var t37 int32
								if t35 == i32_const(7) {
									t38 := v4
									m.Memory[uint32(t38+24)] = byte(i32_const(1))
									t40 := m._sql3lexer_next(v0)
									t37 = t40
								} else {
									t41 := v5
									t37 = t41
								}
								if t37 != i32_const(8) {
									goto l1
								}
								t43 := v3
								t44 := t43 + i32_const(12)
								v0 = t44
								t45 := m._sql3lexer_peek(t44)
								if t45 == i32_const(9) {
									t48 := m._sql3lexer_next(v0)
									_ = t48
									v1 = i32_const(2)
									t50 := m._sql3lexer_next(v0)
									if t50 != i32_const(10) {
										goto l1
									}
									t53 := m._sql3lexer_next(v0)
									if t53 != i32_const(11) {
										goto l1
									}
									t55 := v4
									m.Memory[uint32(t55+25)] = byte(i32_const(1))
								}
								t56 := v3
								t57 := t56 + i32_const(12)
								v0 = t57
								t58 := m._sql3parse_schema_identifier(t57)
								v1 = t58
								if t58 != 0 {
									goto l1
								}
								v1 = i32_const(3)
								{
									t60 := m._sql3lexer_next(v0)
									switch t60 - i32_const(15) {
									default:
										goto l2
									case 0:
										goto l1
									case 1:
										goto l2
									case 2:
										goto l2
									case 3:
										goto l2
									case 4:
										goto l3
									}
								}
							l3:
								;
							l6:
								{
									t62 := v3
									t63 := t62 + i32_const(12)
									v0 = t63
									t64 := m._sql3lexer_peek(t63)
									if t64 != i32_const(2) {
										goto l2
									}
									t67 := m._sql3parse_column(v0)
									v5 = t67
									if t67 == 0 {
										goto l2
									}
									t69 := v4
									t71 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v4+28):]))
									t72 := t71 + i32_const(1)
									v0 = t72
									binary.LittleEndian.PutUint32(m.Memory[uint32(t69+28):], uint32(t72))
									t74 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v4+32):]))
									t75 := v0
									t77 := m._realloc(t74, i32_shl(t75, i32_const(2)))
									v0 = t77
									if t77 == 0 {
										t79 := v4
										t81 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v4+28):]))
										binary.LittleEndian.PutUint32(m.Memory[uint32(t79+28):], uint32(t81-i32_const(1)))
										v1 = i32_const(1)
										goto l1
									}
									t83 := v4
									binary.LittleEndian.PutUint32(m.Memory[uint32(t83+32):], uint32(v0))
									v1 = i32_const(2)
									t85 := v0
									t87 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v4+28):]))
									t89 := t85 + i32_shl(t87, i32_const(2))
									t90 := t89 - i32_const(4)
									binary.LittleEndian.PutUint32(m.Memory[uint32(t90):], uint32(v5))
									{
										t92 := v3
										t94 := m._sql3lexer_peek(t92 + i32_const(12))
										switch t94 - i32_const(18) {
										default:
											goto l1
										case 0:
											goto l4
										case 1:
											goto l1
										case 2:
											goto l5
										}
									}
								l4:
									;
									t96 := v3
									t97 := t96 + i32_const(12)
									v0 = t97
									t98 := m._sql3lexer_next(t97)
									_ = t98
									t100 := m._sql3lexer_peek(v0)
									t101 := t100 - i32_const(21)
									v0 = t101
									var t102 int32
									if uint32(t101) > uint32(i32_const(5)) {
										t102 = 1
									}
									t104 := i32_shr_u(i32_const(59), v0)
									var t106 int32
									if t104&i32_const(1) == 0 {
										t106 = 1
									}
									t107 := t102 | t106
									if t107 != 0 {
										goto l6
									}
								}
								t108 := v0
								t110 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(i32_shl(t108, i32_const(2))+65904):]))
								t12 = t110
								goto l7
							}
							v0 = int32(binary.LittleEndian.Uint32(m.Memory[uint32(v3+36):]))
							t113 := v3
							t114 := t113 + i32_const(12)
							v4 = t114
							t115 := m._sql3lexer_next(t114)
							if t115 != i32_const(8) {
								goto l1
							}
							t118 := m._sql3parse_schema_identifier(v4)
							v1 = t118
							if t118 != 0 {
								goto l1
							}
							t120 := m._sql3lexer_next(v4)
							v5 = t120
							t122 := m._sql3lexer_peek(v4)
							v4 = t122
							v1 = i32_const(3)
							{
								{
									{
										{
											t123 := v5
											switch t123 - i32_const(58) {
											default:
												goto l1
											case 0:
												goto l8
											case 1:
												goto l9
											case 2:
												goto l10
											}
										}
									l8:
										;
										{
											{
												{
													t125 := v4
													switch t125 - i32_const(61) {
													default:
														goto l11
													case 0:
														goto l12
													case 1:
														goto l13
													}
												}
											l13:
												;
												t127 := v3
												t128 := t127 + i32_const(12)
												v4 = t128
												t129 := m._sql3lexer_next(t128)
												_ = t129
												v1 = i32_const(2)
												t130 := v0
												binary.LittleEndian.PutUint32(m.Memory[uint32(t130+44):], uint32(i32_const(2)))
												t132 := m._sql3lexer_next(v4)
												if t132 != i32_const(2) {
													goto l1
												}
												t134 := v0
												binary.LittleEndian.PutUint64(m.Memory[uint32(t134+56):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v3+24):]))))
												goto l14
											}
										l12:
											;
											t137 := v3
											t139 := m._sql3lexer_next(t137 + i32_const(12))
											_ = t139
										}
									l11:
										;
										t140 := v0
										binary.LittleEndian.PutUint32(m.Memory[uint32(t140+44):], uint32(i32_const(3)))
										v1 = i32_const(2)
										t141 := v3
										t142 := t141 + i32_const(12)
										v4 = t142
										t143 := m._sql3lexer_next(t142)
										if t143 != i32_const(2) {
											goto l1
										}
										t145 := v0
										binary.LittleEndian.PutUint64(m.Memory[uint32(t145+48):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v3+24):]))))
										t149 := m._sql3lexer_next(v4)
										if t149 != i32_const(62) {
											goto l1
										}
										t152 := m._sql3lexer_next(v4)
										if t152 != i32_const(2) {
											goto l1
										}
										t154 := v0
										binary.LittleEndian.PutUint64(m.Memory[uint32(t154+56):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v3+24):]))))
										goto l14
									}
								l9:
									;
									t157 := v4
									if t157 == i32_const(61) {
										t159 := v3
										t161 := m._sql3lexer_next(t159 + i32_const(12))
										_ = t161
									}
									t162 := v0
									binary.LittleEndian.PutUint32(m.Memory[uint32(t162+44):], uint32(i32_const(4)))
									v1 = i32_const(2)
									t163 := v3
									t164 := t163 + i32_const(12)
									v4 = t164
									t165 := m._sql3lexer_peek(t164)
									if t165 != i32_const(2) {
										goto l1
									}
									t168 := m._sql3parse_column(v4)
									v5 = t168
									if t168 == 0 {
										goto l1
									}
									v1 = i32_const(1)
									t170 := v0
									t172 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+28):]))
									t173 := t172 + i32_const(1)
									v4 = t173
									binary.LittleEndian.PutUint32(m.Memory[uint32(t170+28):], uint32(t173))
									t175 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+32):]))
									t176 := v4
									t178 := m._realloc(t175, i32_shl(t176, i32_const(2)))
									v4 = t178
									if t178 == 0 {
										t180 := v0
										t182 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+28):]))
										binary.LittleEndian.PutUint32(m.Memory[uint32(t180+28):], uint32(t182-i32_const(1)))
										goto l1
									}
									t184 := v0
									binary.LittleEndian.PutUint32(m.Memory[uint32(t184+32):], uint32(v4))
									t186 := v4
									t188 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+28):]))
									t190 := t186 + i32_shl(t188, i32_const(2))
									t191 := t190 - i32_const(4)
									binary.LittleEndian.PutUint32(m.Memory[uint32(t191):], uint32(v5))
									goto l14
								}
							l10:
								;
								t193 := v4
								if t193 == i32_const(61) {
									t195 := v3
									t197 := m._sql3lexer_next(t195 + i32_const(12))
									_ = t197
								}
								t198 := v0
								binary.LittleEndian.PutUint32(m.Memory[uint32(t198+44):], uint32(i32_const(5)))
								v1 = i32_const(2)
								t199 := v3
								t201 := m._sql3lexer_next(t199 + i32_const(12))
								if t201 != i32_const(2) {
									goto l1
								}
								t203 := v0
								binary.LittleEndian.PutUint64(m.Memory[uint32(t203+48):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v3+24):]))))
							}
						l14:
							;
							v1 = i32_const(0)
							t206 := v3
							t207 := t206 + i32_const(12)
							v0 = t207
							t208 := m._sql3lexer_peek(t207)
							if t208 != i32_const(17) {
								goto l1
							}
							t211 := m._sql3lexer_next(v0)
							_ = t211
							goto l1
						}
						if v2 == 0 {
							goto l0
						}
						t214 := v2
						binary.LittleEndian.PutUint32(m.Memory[uint32(t214):], uint32(i32_const(1)))
						goto l0
					}
				l5:
					;
					t215 := v3
					t217 := m._sql3lexer_peek(t215 + i32_const(12))
					t12 = t217
				}
			l7:
				;
				v1 = t12
				t218 := v4
				v9 = t218 + i32_const(16)
				t220 := v3
				v10 = t220 + i32_const(56)
			l27:
				{
					{
						t223 := i32_shl(i32_const(1), v1)
						var t225 int32
						if t223&i32_const(123731968) == 0 {
							t225 = 1
						}
						t226 := v1
						var t227 int32
						if uint32(t226) > uint32(i32_const(26)) {
							t227 = 1
						}
						if t225|t227 == 0 {
							t230 := v3
							binary.LittleEndian.PutUint32(m.Memory[uint32(t230+32):], uint32(v9))
							t232 := v3
							t233 := t232 + i32_const(12)
							v5 = t233
							t234 := m._sql3lexer_peek(t233)
							v1 = t234
							t235 := m._malloc(i32_const(28))
							v0 = t235
							if t235 == 0 {
								goto l2
							}
							{
								{
									{
										{
											t237 := v1
											var t239 int32
											if t237 == i32_const(21) {
												t241 := m._sql3lexer_next(v5)
												_ = t241
												v1 = i32_const(2)
												t243 := m._sql3lexer_next(v5)
												if t243 != i32_const(2) {
													goto l1
												}
												t245 := v0
												binary.LittleEndian.PutUint64(m.Memory[uint32(t245+4):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v3+24):]))))
												t249 := m._sql3lexer_peek(v5)
												t250 := t249 - i32_const(22)
												v5 = t250
												var t251 int32
												if uint32(t250) > uint32(i32_const(4)) {
													t251 = 1
												}
												t253 := i32_shr_u(i32_const(29), v5)
												var t255 int32
												if t253&i32_const(1) == 0 {
													t255 = 1
												}
												t256 := t251 | t255
												if t256 != 0 {
													goto l1
												}
												t257 := v5
												t259 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(i32_shl(t257, i32_const(2))+65928):]))
												t239 = t259
											} else {
												t260 := v1
												t239 = t260
											}
											switch t239 - i32_const(22) {
											default:
												goto l15
											case 0:
												goto l16
											case 1:
												goto l15
											case 2:
												goto l16
											case 3:
												goto l17
											case 4:
												goto l18
											}
										}
									l17:
										;
										t262 := v3
										t263 := t262 + i32_const(12)
										v1 = t263
										t264 := m._sql3lexer_next(t263)
										_ = t264
										t265 := v0
										binary.LittleEndian.PutUint32(m.Memory[uint32(t265):], uint32(i32_const(2)))
										t266 := v0
										t267 := t266 + i32_const(12)
										m._sql3parse_expression(t267, v1)
										goto l15
									}
								l16:
									;
									t269 := v0
									t270 := v3
									t272 := m._sql3lexer_next(t270 + i32_const(12))
									var t273 int32
									if t272 != i32_const(22) {
										t273 = 1
									}
									v6 = t273
									var t274 int32
									if t273 != 0 {
										t274 = i32_const(1)
									} else {
										t275 := v3
										t277 := m._sql3lexer_next(t275 + i32_const(12))
										if t277 != i32_const(23) {
											goto l2
										}
										t274 = i32_const(0)
									}
									binary.LittleEndian.PutUint32(m.Memory[uint32(t269):], uint32(t274))
									t279 := v3
									t281 := m._sql3lexer_next(t279 + i32_const(12))
									if t281 != i32_const(19) {
										goto l2
									}
								l19:
									{
										t283 := v3
										binary.LittleEndian.PutUint64(m.Memory[uint32(t283+48):], uint64(i64_const(0)))
										t284 := v3
										t285 := t284 + i32_const(12)
										v1 = t285
										t286 := m._sql3lexer_next(t285)
										if t286 != i32_const(2) {
											goto l2
										}
										t288 := v3
										binary.LittleEndian.PutUint64(m.Memory[uint32(t288+40):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v3+24):]))))
										t292 := m._sql3lexer_peek(v1)
										if t292 == i32_const(34) {
											t295 := m._sql3lexer_next(v1)
											_ = t295
											t297 := m._sql3lexer_next(v1)
											if t297 != i32_const(2) {
												goto l2
											}
											t299 := v3
											binary.LittleEndian.PutUint64(m.Memory[uint32(t299+48):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v3+24):]))))
										}
										t302 := v3
										t303 := t302 + i32_const(12)
										v1 = t303
										m._sql3parse_optionalorder(t303, v10)
										t305 := v0
										t307 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+12):]))
										v7 = t307
										t308 := t307 + i32_const(1)
										v5 = t308
										binary.LittleEndian.PutUint32(m.Memory[uint32(t305+12):], uint32(t308))
										t310 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+16):]))
										t311 := v5
										t312 := t311 * i32_const(20)
										v11 = t312
										t313 := m._realloc(t310, t312)
										v5 = t313
										if t313 == 0 {
											goto l2
										}
										t315 := v0
										binary.LittleEndian.PutUint32(m.Memory[uint32(t315+16):], uint32(v5))
										t317 := v5
										t319 := t317 + v11
										t320 := t319 - i32_const(20)
										v5 = t320
										binary.LittleEndian.PutUint64(m.Memory[uint32(t320):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v3+40):]))))
										t323 := v5
										t324 := t323 + i32_const(16)
										binary.LittleEndian.PutUint32(m.Memory[uint32(t324):], uint32(int32(binary.LittleEndian.Uint32(m.Memory[uint32(v10):]))))
										t327 := v5
										t328 := t327 + i32_const(8)
										t329 := v3
										binary.LittleEndian.PutUint64(m.Memory[uint32(t328):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(t329+i32_const(48)):]))))
										t333 := m._sql3lexer_peek(v1)
										v5 = t333
										var t335 int32
										if t333 == i32_const(37) {
											t337 := m._sql3lexer_next(v1)
											_ = t337
											t338 := v6
											if t338 != 0 {
												goto l2
											}
											t339 := v0
											m.Memory[uint32(t339+24)] = byte(i32_const(1))
											t341 := m._sql3lexer_peek(v1)
											t335 = t341
										} else {
											t342 := v5
											t335 = t342
										}
										if t335 == i32_const(18) {
											t344 := v3
											t346 := m._sql3lexer_next(t344 + i32_const(12))
											_ = t346
											goto l19
										}
									}
									t347 := v7
									if t347 != 0 {
										t349 := int32(m.Memory[uint32(v0+24)])
										t350 := t349 & i32_const(1)
										if t350 != 0 {
											goto l2
										}
									}
									t351 := v3
									t352 := t351 + i32_const(12)
									v1 = t352
									t353 := m._sql3lexer_next(t352)
									if t353 != i32_const(20) {
										goto l2
									}
									t355 := v1
									t356 := v0
									t358 := m._sql3parse_optionalconflitclause(t355, t356+i32_const(20))
									if t358 == 0 {
										goto l15
									}
									goto l2
								}
							l18:
								;
								t360 := v3
								t361 := t360 + i32_const(12)
								v1 = t361
								t362 := m._sql3lexer_next(t361)
								_ = t362
								t364 := m._sql3lexer_next(v1)
								if t364 != i32_const(23) {
									goto l2
								}
								t367 := m._sql3lexer_next(v1)
								if t367 != i32_const(19) {
									goto l2
								}
								t369 := v0
								binary.LittleEndian.PutUint32(m.Memory[uint32(t369):], uint32(i32_const(3)))
							l20:
								{
									v1 = i32_const(2)
									t370 := v3
									t371 := t370 + i32_const(12)
									v5 = t371
									t372 := m._sql3lexer_next(t371)
									if t372 != i32_const(2) {
										goto l1
									}
									t374 := v0
									t376 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+12):]))
									t377 := t376 + i32_const(1)
									v6 = t377
									binary.LittleEndian.PutUint32(m.Memory[uint32(t374+12):], uint32(t377))
									t379 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+16):]))
									t380 := v6
									t381 := i32_shl(t380, i32_const(3))
									v7 = t381
									t382 := m._realloc(t379, t381)
									v6 = t382
									if t382 == 0 {
										goto l1
									}
									t384 := v0
									binary.LittleEndian.PutUint32(m.Memory[uint32(t384+16):], uint32(v6))
									t386 := v6
									t388 := t386 + v7
									t389 := t388 - i32_const(8)
									binary.LittleEndian.PutUint64(m.Memory[uint32(t389):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v3+24):]))))
									t393 := m._sql3lexer_peek(v5)
									t395 := m._sql3lexer_next(v5)
									v7 = t395
									if t393 == i32_const(18) {
										goto l20
									}
								}
								t397 := v7
								if t397 != i32_const(20) {
									goto l1
								}
								t400 := m._sql3lexer_next(v5)
								if t400 != i32_const(42) {
									goto l1
								}
								t403 := m._sql3parse_foreignkey_clause(v5)
								v5 = t403
								if t403 == 0 {
									goto l1
								}
								t405 := v0
								binary.LittleEndian.PutUint32(m.Memory[uint32(t405+20):], uint32(v5))
							}
						l15:
							;
							t407 := v4
							t409 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v4+36):]))
							t410 := t409 + i32_const(1)
							v1 = t410
							binary.LittleEndian.PutUint32(m.Memory[uint32(t407+36):], uint32(t410))
							t412 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v4+40):]))
							t413 := v1
							t415 := m._realloc(t412, i32_shl(t413, i32_const(2)))
							v1 = t415
							if t415 == 0 {
								t417 := v4
								t419 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v4+36):]))
								binary.LittleEndian.PutUint32(m.Memory[uint32(t417+36):], uint32(t419-i32_const(1)))
								v1 = i32_const(1)
								goto l1
							}
							t421 := v4
							binary.LittleEndian.PutUint32(m.Memory[uint32(t421+40):], uint32(v1))
							t423 := v1
							t425 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v4+36):]))
							t427 := t423 + i32_shl(t425, i32_const(2))
							t428 := t427 - i32_const(4)
							binary.LittleEndian.PutUint32(m.Memory[uint32(t428):], uint32(v0))
							t430 := v3
							t431 := t430 + i32_const(12)
							v0 = t431
							t432 := m._sql3lexer_peek(t431)
							if t432 == i32_const(18) {
								goto l21
							}
							v1 = i32_const(2)
							t435 := m._sql3lexer_peek(v0)
							if t435 != i32_const(20) {
								goto l1
							}
						}
						v1 = i32_const(2)
						t437 := v3
						t439 := m._sql3lexer_next(t437 + i32_const(12))
						if t439 != i32_const(20) {
							goto l1
						}
						t441 := v3
						binary.LittleEndian.PutUint32(m.Memory[uint32(t441+32):], uint32(v9))
					l26:
						{
							{
								{
									{
										{
											t443 := v3
											t445 := m._sql3lexer_peek(t443 + i32_const(12))
											switch t445 - i32_const(12) {
											default:
												goto l22
											case 0:
												goto l23
											case 1:
												goto l22
											case 2:
												goto l24
											}
										}
									l23:
										;
										t447 := v3
										t448 := t447 + i32_const(12)
										v0 = t448
										t449 := m._sql3lexer_next(t448)
										_ = t449
										t451 := m._sql3lexer_next(v0)
										if t451 != i32_const(13) {
											goto l1
										}
										t454 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v3+36):]))
										m.Memory[uint32(t454+26)] = byte(i32_const(1))
										goto l25
									}
								l24:
									;
									t455 := v3
									t457 := m._sql3lexer_next(t455 + i32_const(12))
									_ = t457
									t459 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v3+36):]))
									m.Memory[uint32(t459+27)] = byte(i32_const(1))
								}
							l25:
								;
								t460 := v3
								t461 := t460 + i32_const(12)
								v0 = t461
								t462 := m._sql3lexer_peek(t461)
								if t462 != i32_const(18) {
									goto l22
								}
								t465 := m._sql3lexer_next(v0)
								_ = t465
								goto l26
							}
						l22:
						}
						v1 = i32_const(0)
						t466 := v3
						t467 := t466 + i32_const(12)
						v0 = t467
						t468 := m._sql3lexer_peek(t467)
						if t468 != i32_const(17) {
							goto l1
						}
						t471 := m._sql3lexer_next(v0)
						_ = t471
						goto l1
					}
				l21:
					;
					t472 := v3
					t473 := t472 + i32_const(12)
					v0 = t473
					t474 := m._sql3lexer_next(t473)
					_ = t474
					t476 := m._sql3lexer_peek(v0)
					v1 = t476
					goto l27
				}
			}
		l2:
			;
			v1 = i32_const(2)
		}
	l1:
		;
		t477 := v2
		if t477 != 0 {
			t478 := v2
			binary.LittleEndian.PutUint32(m.Memory[uint32(t478):], uint32(v1))
		}
		t480 := v8
		t481 := v1
		t482 := t480
		if t481 != 0 {
			t482 = i32_const(0)
		}
		v4 = t482
	}
l0:
	;
	t483 := v3
	m.___stack_pointer = t483 - i32_const(-64)
	t485 := v4
	return t485
}
func (m Module) _sql3lexer_next(v0 int32) int32 {
	var v1, v2, v3, v4, v5, v6, v7, v8 int32
	_, _, _, _, _, _, _, _ = v1, v2, v3, v4, v5, v6, v7, v8
	{
		{
			{
				{
				l1:
					{
						t1 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+8):]))
						v5 = t1
						t3 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+4):]))
						v6 = t3
						if uint32(t1) >= uint32(t3) {
							goto l0
						}
						t6 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0):]))
						v7 = t6
						t8 := t6 + v5
						v1 = t8
						t9 := int32(m.Memory[uint32(t8)])
						v2 = t9
						if t9 == 0 {
							goto l0
						}
						t12 := m._symbol_is_toskip(v2)
						if t12 != 0 {
							t13 := v0
							t14 := v5
							binary.LittleEndian.PutUint32(m.Memory[uint32(t13+8):], uint32(t14+i32_const(1)))
							goto l1
						}
						t16 := v2
						t18 := m._symbol_is_comment(t16, v0)
						if t18 != 0 {
							m._sql3lexer_comment(v0)
							goto l1
						}
					}
					t20 := v2
					var t21 int32
					if t20 == i32_const(59) {
						t21 = 1
					}
					t22 := v2
					t23 := t22 & i32_const(253)
					var t24 int32
					if t23 == i32_const(44) {
						t24 = 1
					}
					var t26 int32
					if t21|t24 == 0 {
						t26 = 1
					}
					t27 := v2
					t28 := t27 & i32_const(254)
					var t29 int32
					if t28 != i32_const(40) {
						t29 = 1
					}
					if t26&t29 == 0 {
						t32 := v0
						t33 := v5
						binary.LittleEndian.PutUint32(m.Memory[uint32(t32+8):], uint32(t33+i32_const(1)))
						v4 = i32_const(18)
						{
							{
								{
									{
										t36 := int32(m.Memory[uint32(v1)])
										v0 = t36
										switch t36 - i32_const(40) {
										default:
											goto l2
										case 0:
											goto l3
										case 1:
											goto l4
										case 2:
											goto l5
										case 3:
											goto l5
										case 4:
											goto l0
										case 5:
											goto l5
										case 6:
											goto l6
										}
									}
								l6:
									;
									return i32_const(16)
								}
							l3:
								;
								return i32_const(19)
							}
						l4:
							;
							return i32_const(20)
						}
					l2:
						;
						t38 := v0
						if t38 == i32_const(59) {
							goto l7
						}
						goto l5
					}
					{
						t40 := v2
						var t41 int32
						if t40 != i32_const(95) {
							t41 = 1
						}
						t42 := v2
						t43 := t42 | i32_const(32)
						t44 := t43 - i32_const(97)
						var t45 int32
						if uint32(t44) > uint32(i32_const(25)) {
							t45 = 1
						}
						if t41&t45 == 0 {
						l8:
							{
								v2 = i32_const(0)
								t48 := v6
								t49 := v3
								t51 := t49 + v5
								v4 = t51
								if uint32(t48) > uint32(t51) {
									t53 := v1
									v2 = int32(m.Memory[uint32(t53+v3)])
								}
								t57 := v2
								var t58 int32
								if t57 == i32_const(95) {
									t58 = 1
								}
								t59 := v2
								t60 := t59 | i32_const(32)
								t61 := t60 - i32_const(97)
								var t62 int32
								if uint32(t61) < uint32(i32_const(26)) {
									t62 = 1
								}
								var t64 int32
								if t58|t62 == 0 {
									t64 = 1
								}
								t65 := v2
								t66 := t65 - i32_const(48)
								var t67 int32
								if uint32(t66) > uint32(i32_const(9)) {
									t67 = 1
								}
								if t64&t67 == 0 {
									t70 := v0
									t71 := v4
									binary.LittleEndian.PutUint32(m.Memory[uint32(t70+8):], uint32(t71+i32_const(1)))
									t73 := v3
									v3 = t73 + i32_const(1)
									goto l8
								}
							}
							{
								{
									{
										{
											{
												{
													{
														{
															{
																{
																	{
																		t75 := v3
																		switch t75 - i32_const(2) {
																		default:
																			goto l9
																		case 0:
																			goto l10
																		case 1:
																			goto l11
																		case 2:
																			goto l12
																		case 3:
																			goto l13
																		case 4:
																			goto l14
																		case 5:
																			goto l15
																		case 6:
																			goto l16
																		case 7:
																			goto l17
																		case 8:
																			goto l18
																		case 9:
																			goto l9
																		case 10:
																			goto l9
																		case 11:
																			goto l19
																		}
																	}
																l10:
																	;
																	t77 := v1
																	t78 := m._str_nocasencmp(t77, i32_const(65752), i32_const(2))
																	if t78 == 0 {
																		return i32_const(9)
																	}
																	t80 := v1
																	t81 := m._str_nocasencmp(t80, i32_const(65695), i32_const(2))
																	if t81 == 0 {
																		return i32_const(27)
																	}
																	t83 := v1
																	t84 := m._str_nocasencmp(t83, i32_const(65688), i32_const(2))
																	if t84 == 0 {
																		return i32_const(50)
																	}
																	t86 := v1
																	t87 := m._str_nocasencmp(t86, i32_const(65666), i32_const(2))
																	if t87 == 0 {
																		return i32_const(15)
																	}
																	t89 := v1
																	t90 := m._str_nocasencmp(t89, i32_const(65685), i32_const(2))
																	if t90 != 0 {
																		goto l9
																	}
																	return i32_const(62)
																}
															l11:
																;
																t91 := v1
																t92 := m._str_nocasencmp(t91, i32_const(65582), i32_const(3))
																if t92 == 0 {
																	return i32_const(10)
																}
																t94 := v1
																t95 := m._str_nocasencmp(t94, i32_const(65564), i32_const(3))
																if t95 == 0 {
																	return i32_const(23)
																}
																t97 := v1
																t98 := m._str_nocasencmp(t97, i32_const(65889), i32_const(3))
																if t98 == 0 {
																	return i32_const(35)
																}
																t100 := v1
																t101 := m._str_nocasencmp(t100, i32_const(65619), i32_const(3))
																if t101 == 0 {
																	return i32_const(45)
																}
																t103 := v1
																t104 := m._str_nocasencmp(t103, i32_const(65880), i32_const(3))
																if t104 != 0 {
																	goto l9
																}
																return i32_const(59)
															}
														l12:
															;
															t105 := v1
															t106 := m._str_nocasencmp(t105, i32_const(65680), i32_const(4))
															if t106 == 0 {
																goto l20
															}
															t108 := v1
															t109 := m._str_nocasencmp(t108, i32_const(65884), i32_const(4))
															if t109 == 0 {
																return i32_const(36)
															}
															t111 := v1
															t112 := m._str_nocasencmp(t111, i32_const(65713), i32_const(4))
															if t112 == 0 {
																return i32_const(46)
															}
															t114 := v1
															t115 := m._str_nocasencmp(t114, i32_const(65718), i32_const(4))
															if t115 == 0 {
																return i32_const(31)
															}
															t117 := v1
															t118 := m._str_nocasencmp(t117, i32_const(65675), i32_const(4))
															if t118 != 0 {
																goto l9
															}
															return i32_const(60)
														}
													l13:
														;
														t119 := v1
														t120 := m._str_nocasencmp(t119, i32_const(65815), i32_const(5))
														if t120 == 0 {
															return i32_const(8)
														}
														t122 := v1
														t123 := m._str_nocasencmp(t122, i32_const(65848), i32_const(5))
														if t123 == 0 {
															return i32_const(13)
														}
														t125 := v1
														t126 := m._str_nocasencmp(t125, i32_const(65731), i32_const(5))
														if t126 == 0 {
															return i32_const(25)
														}
														t128 := v1
														t129 := m._str_nocasencmp(t128, i32_const(65576), i32_const(5))
														if t129 == 0 {
															return i32_const(30)
														}
														t131 := v1
														t132 := m._str_nocasencmp(t131, i32_const(65746), i32_const(5))
														if t132 == 0 {
															return i32_const(52)
														}
														t134 := v1
														t135 := m._str_nocasencmp(t134, i32_const(65669), i32_const(5))
														if t135 != 0 {
															goto l9
														}
														return i32_const(57)
													}
												l14:
													;
													v4 = i32_const(6)
													t136 := v1
													t137 := m._str_nocasencmp(t136, i32_const(65787), i32_const(6))
													if t137 == 0 {
														goto l0
													}
													t139 := v1
													t140 := m._str_nocasencmp(t139, i32_const(65648), i32_const(6))
													if t140 == 0 {
														return i32_const(11)
													}
													t142 := v1
													t143 := m._str_nocasencmp(t142, i32_const(65755), i32_const(6))
													if t143 == 0 {
														return i32_const(24)
													}
													t145 := v1
													t146 := m._str_nocasencmp(t145, i32_const(65801), i32_const(6))
													if t146 == 0 {
														return i32_const(32)
													}
													t148 := v1
													t149 := m._str_nocasencmp(t148, i32_const(65762), i32_const(6))
													if t149 == 0 {
														return i32_const(43)
													}
													t151 := v1
													t152 := m._str_nocasencmp(t151, i32_const(65794), i32_const(6))
													if t152 == 0 {
														return i32_const(44)
													}
													t154 := v1
													t155 := m._str_nocasencmp(t154, i32_const(65691), i32_const(6))
													if t155 == 0 {
														return i32_const(51)
													}
													t157 := v1
													t158 := m._str_nocasencmp(t157, i32_const(65625), i32_const(6))
													if t158 == 0 {
														return i32_const(14)
													}
													t160 := v1
													t161 := m._str_nocasencmp(t160, i32_const(65808), i32_const(6))
													if t161 == 0 {
														return i32_const(58)
													}
													t163 := v1
													t164 := m._str_nocasencmp(t163, i32_const(65698), i32_const(6))
													if t164 == 0 {
														return i32_const(61)
													}
													t166 := v1
													t167 := m._str_nocasencmp(t166, i32_const(65641), i32_const(6))
													if t167 == 0 {
														return i32_const(39)
													}
													t169 := v1
													t170 := m._str_nocasencmp(t169, i32_const(65873), i32_const(6))
													if t170 != 0 {
														goto l9
													}
													return i32_const(40)
												}
											l15:
												;
												t171 := v1
												t172 := m._str_nocasencmp(t171, i32_const(65568), i32_const(7))
												if t172 == 0 {
													return i32_const(12)
												}
												t174 := v1
												t175 := m._str_nocasencmp(t174, i32_const(65546), i32_const(7))
												if t175 == 0 {
													return i32_const(22)
												}
												t177 := v1
												t178 := m._str_nocasencmp(t177, i32_const(65611), i32_const(7))
												if t178 == 0 {
													return i32_const(47)
												}
												t180 := v1
												t181 := m._str_nocasencmp(t180, i32_const(65769), i32_const(7))
												if t181 == 0 {
													return i32_const(34)
												}
												t183 := v1
												t184 := m._str_nocasencmp(t183, i32_const(65840), i32_const(7))
												if t184 == 0 {
													return i32_const(33)
												}
												t186 := v1
												t187 := m._str_nocasencmp(t186, i32_const(65832), i32_const(7))
												if t187 == 0 {
													return i32_const(48)
												}
												t189 := v1
												t190 := m._str_nocasencmp(t189, i32_const(65705), i32_const(7))
												if t190 == 0 {
													return i32_const(26)
												}
												t192 := v1
												t193 := m._str_nocasencmp(t192, i32_const(65723), i32_const(7))
												if t193 != 0 {
													goto l9
												}
												return i32_const(41)
											}
										l16:
											;
											t194 := v1
											t195 := m._str_nocasencmp(t194, i32_const(65632), i32_const(8))
											if t195 == 0 {
												return i32_const(28)
											}
											t197 := v1
											t198 := m._str_nocasencmp(t197, i32_const(65737), i32_const(8))
											if t198 == 0 {
												return i32_const(29)
											}
											t200 := v1
											t201 := m._str_nocasencmp(t200, i32_const(65623), i32_const(8))
											if t201 == 0 {
												return i32_const(49)
											}
											t203 := v1
											t204 := m._str_nocasencmp(t203, i32_const(65864), i32_const(8))
											if t204 != 0 {
												goto l9
											}
											return i32_const(55)
										}
									l17:
										;
										t205 := v1
										t206 := m._str_nocasencmp(t205, i32_const(65536), i32_const(9))
										if t206 == 0 {
											goto l20
										}
										t208 := v1
										t209 := m._str_nocasencmp(t208, i32_const(65554), i32_const(9))
										if t209 == 0 {
											return i32_const(54)
										}
										t211 := v1
										t212 := m._str_nocasencmp(t211, i32_const(65777), i32_const(9))
										if t212 == 0 {
											return i32_const(56)
										}
										t214 := v1
										t215 := m._str_nocasencmp(t214, i32_const(65854), i32_const(9))
										if t215 != 0 {
											goto l9
										}
										return i32_const(38)
									}
								l18:
									;
									t216 := v1
									t217 := m._str_nocasencmp(t216, i32_const(65586), i32_const(10))
									if t217 == 0 {
										return i32_const(21)
									}
									t219 := v1
									t220 := m._str_nocasencmp(t219, i32_const(65655), i32_const(10))
									if t220 == 0 {
										return i32_const(42)
									}
									t222 := v1
									t223 := m._str_nocasencmp(t222, i32_const(65821), i32_const(10))
									if t223 != 0 {
										goto l9
									}
									return i32_const(53)
								}
							l19:
								;
								t224 := v1
								t225 := m._str_nocasencmp(t224, i32_const(65597), i32_const(13))
								if t225 != 0 {
									goto l9
								}
								return i32_const(37)
							}
						l9:
							;
							t226 := v0
							binary.LittleEndian.PutUint32(m.Memory[uint32(t226+16):], uint32(v3))
							t228 := v0
							binary.LittleEndian.PutUint32(m.Memory[uint32(t228+12):], uint32(v1))
							goto l21
						}
						t230 := v2
						var t231 int32
						if t230 == i32_const(34) {
							t231 = 1
						}
						t232 := v2
						var t233 int32
						if t232 == i32_const(39) {
							t233 = 1
						}
						t234 := t231 | t233
						t235 := v2
						var t236 int32
						if t235 == i32_const(96) {
							t236 = 1
						}
						var t238 int32
						if t234|t236 == 0 {
							t238 = 1
						}
						t239 := v2
						var t240 int32
						if t239 != i32_const(91) {
							t240 = 1
						}
						t241 := t238 & t240
						if t241 != 0 {
							goto l5
						}
						t242 := v0
						t243 := v5
						t244 := t243 + i32_const(1)
						v4 = t244
						binary.LittleEndian.PutUint32(m.Memory[uint32(t242+8):], uint32(t244))
						t246 := int32(m.Memory[uint32(v1)])
						v2 = t246
						t247 := v2
						t249 := t246
						if t247 == i32_const(91) {
							t249 = i32_const(93)
						}
						v8 = t249 & i32_const(255)
						v2 = v4
						{
						l23:
							{
								t252 := v6
								t253 := v2
								v1 = t253
								if uint32(t252) > uint32(t253) {
									{
										t255 := v0
										t256 := v1
										t257 := t256 + i32_const(1)
										v2 = t257
										binary.LittleEndian.PutUint32(m.Memory[uint32(t255+8):], uint32(t257))
										t258 := v1
										t261 := int32(m.Memory[uint32(t258+v7)])
										v3 = t261
										if t261 == 0 {
											v3 = i32_const(0)
											goto l22
										}
										t263 := v3
										if t263 != v8 {
											goto l23
										}
										t266 := v2
										if uint32(t266) >= uint32(v6) {
											goto l24
										}
										t269 := v8
										t270 := v2
										if t269 != int32(m.Memory[uint32(t270+v7)]) {
											goto l24
										}
										t275 := v0
										t276 := v1
										t277 := t276 + i32_const(2)
										v2 = t277
										binary.LittleEndian.PutUint32(m.Memory[uint32(t275+8):], uint32(t277))
										goto l23
									}
								l22:
								}
							}
							t278 := v3
							if t278 != v8 {
								goto l5
							}
						}
					l24:
						;
						t281 := v0
						t282 := v4
						binary.LittleEndian.PutUint32(m.Memory[uint32(t281+12):], uint32(t282+v7))
						t285 := v0
						t286 := v2
						t288 := t286 - v5
						binary.LittleEndian.PutUint32(m.Memory[uint32(t285+16):], uint32(t288-i32_const(2)))
					}
				l21:
					;
					v4 = i32_const(2)
				}
			l0:
				;
				t290 := v4
				return t290
			}
		l20:
			;
			return i32_const(7)
		}
	l5:
		;
		return i32_const(1)
	}
l7:
	;
	return i32_const(17)
}
func (m Module) _sql3lexer_peek(v0 int32) int32 {
	var v1, v2, v3 int32
	_, _, _ = v1, v2, v3
	var v4 int64
	_ = v4
	v1 = int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+8):]))
	v4 = int64(binary.LittleEndian.Uint64(m.Memory[uint32(v0+12):]))
	v2 = int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+20):]))
	t7 := m._sql3lexer_next(v0)
	t8 := v0
	binary.LittleEndian.PutUint32(m.Memory[uint32(t8+20):], uint32(v2))
	t10 := v0
	binary.LittleEndian.PutUint64(m.Memory[uint32(t10+12):], uint64(v4))
	t12 := v0
	binary.LittleEndian.PutUint32(m.Memory[uint32(t12+8):], uint32(v1))
	return t7
}
func (m Module) _sql3parse_schema_identifier(v0 int32) int32 {
	var v1, v2, v3, v4 int32
	_, _, _, _ = v1, v2, v3, v4
	v4 = int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+24):]))
	{
		t3 := m._sql3lexer_next(v0)
		v1 = t3
		if t3 != i32_const(7) {
			v2 = i32_const(2)
			t5 := v1
			if t5 != i32_const(2) {
				goto l0
			}
		}
		v2 = i32_const(2)
		t7 := v1
		if t7 == i32_const(2) {
			if int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+12):])) == 0 {
				goto l0
			}
		}
		{
			t13 := m._sql3lexer_peek(v0)
			if t13 == i32_const(16) {
				t16 := m._sql3lexer_next(v0)
				_ = t16
				t17 := v4
				t18 := v0
				t19 := t18 + i32_const(12)
				v3 = t19
				t20 := v1
				t22 := t19
				if t20 != i32_const(2) {
					t22 = i32_const(65896)
				}
				binary.LittleEndian.PutUint64(m.Memory[uint32(t17+8):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(t22):]))))
				t25 := m._sql3lexer_next(v0)
				if t25 != i32_const(2) {
					goto l0
				}
				t28 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v3):]))
				if t28 != 0 {
					goto l1
				}
				goto l0
			}
			t29 := v0
			t30 := t29 + i32_const(12)
			t31 := v1
			t33 := t30
			if t31 != i32_const(2) {
				t33 = i32_const(65896)
			}
			v3 = t33
		}
	l1:
		;
		t34 := v4
		binary.LittleEndian.PutUint64(m.Memory[uint32(t34):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v3):]))))
		v2 = i32_const(0)
	}
l0:
	;
	t37 := v2
	return t37
}
func (m Module) _sql3parse_column(v0 int32) int32 {
	var v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13 int32
	_, _, _, _, _, _, _, _, _, _, _, _, _ = v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13
	var v14 int64
	_ = v14
	t0 := m.___stack_pointer
	t1 := t0 - i32_const(16)
	v5 = t1
	m.___stack_pointer = t1
	{
		t2 := m._malloc(i32_const(148))
		v2 = t2
		if t2 == 0 {
			goto l0
		}
		t4 := v0
		t5 := v2
		binary.LittleEndian.PutUint32(m.Memory[uint32(t4+20):], uint32(t5+i32_const(24)))
		t8 := m._sql3lexer_next(v0)
		if t8 != i32_const(2) {
			goto l0
		}
		t10 := v2
		binary.LittleEndian.PutUint64(m.Memory[uint32(t10):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v0+12):]))))
		{
			t14 := m._sql3lexer_peek(v0)
			if t14 != i32_const(2) {
				goto l1
			}
		l2:
			{
				t17 := m._sql3lexer_peek(v0)
				if t17 == i32_const(2) {
					t20 := m._sql3lexer_next(v0)
					_ = t20
					t21 := v1
					if t21 != 0 {
						goto l2
					}
					t23 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+8):]))
					v1 = t23 - int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+16):]))
					goto l2
				}
			}
			t27 := v2
			t29 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+8):]))
			binary.LittleEndian.PutUint32(m.Memory[uint32(t27+12):], uint32(t29-v1))
			t32 := v2
			t34 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0):]))
			binary.LittleEndian.PutUint32(m.Memory[uint32(t32+8):], uint32(t34+v1))
			t38 := m._sql3lexer_peek(v0)
			if t38 != i32_const(19) {
				goto l1
			}
			t41 := m._sql3lexer_next(v0)
			_ = t41
			t43 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+8):]))
			v6 = t43
			t44 := v6
			t46 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+4):]))
			v1 = t46
			t47 := v1
			t50 := t46
			if uint32(t47) < uint32(v6) {
				t50 = t44
			}
			v11 = t43 - t50
			v1 = i32_const(0)
		l3:
			{
				t52 := v1
				if t52+v11 == 0 {
					goto l0
				}
				t56 := v0
				t57 := v1
				t59 := t57 + v6
				v4 = t59
				binary.LittleEndian.PutUint32(m.Memory[uint32(t56+8):], uint32(t59+i32_const(1)))
				t61 := v4
				t63 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0):]))
				v12 = t63
				t65 := int32(m.Memory[uint32(t61+t63)])
				v4 = t65
				if t65 == 0 {
					goto l0
				}
				t67 := v1
				v1 = t67 + i32_const(1)
				t69 := v4
				if t69 != i32_const(41) {
					goto l3
				}
			}
			t71 := v2
			t72 := v1
			binary.LittleEndian.PutUint32(m.Memory[uint32(t71+20):], uint32(t72-i32_const(1)))
			t74 := v2
			t75 := v6
			binary.LittleEndian.PutUint32(m.Memory[uint32(t74+16):], uint32(t75+v12))
		}
	l1:
		;
		{
			t79 := m._sql3lexer_peek(v0)
			t80 := m._token_is_column_constraint(t79)
			if t80 == 0 {
				goto l4
			}
			t82 := v2
			v13 = t82 + i32_const(48)
			t84 := v2
			v6 = t84 + i32_const(44)
			t86 := v2
			v11 = t86 + i32_const(60)
			t88 := v2
			v12 = t88 + i32_const(72)
		l15:
			{
				t91 := m._sql3lexer_peek(v0)
				t92 := m._token_is_column_constraint(t91)
				if t92 == 0 {
					goto l4
				}
				v14 = i64_const(0)
				t95 := m._sql3lexer_next(v0)
				v1 = t95
				if t95 == i32_const(21) {
					t98 := m._sql3lexer_next(v0)
					if t98 != i32_const(2) {
						v3 = i32_const(0)
						goto l0
					}
					v14 = int64(binary.LittleEndian.Uint64(m.Memory[uint32(v0+12):]))
					t103 := m._sql3lexer_next(v0)
					v1 = t103
				}
				v3 = i32_const(0)
				t104 := v2
				var t105 int32
				{
					{
						{
							{
								{
									{
										{
											{
												{
													{
														{
															{
																t106 := v1
																switch t106 - i32_const(22) {
																default:
																	goto l5
																case 0:
																	goto l6
																case 1:
																	goto l0
																case 2:
																	goto l7
																case 3:
																	goto l8
																}
															}
														l5:
															;
															{
																t108 := v1
																switch t108 - i32_const(38) {
																default:
																	goto l9
																case 0:
																	goto l10
																case 1:
																	goto l0
																case 2:
																	goto l0
																case 3:
																	goto l0
																case 4:
																	goto l11
																}
															}
														l9:
															;
															t110 := v1
															if t110 == i32_const(10) {
																goto l12
															}
															t112 := v1
															if t112 == i32_const(15) {
																goto l10
															}
															t114 := v1
															if t114 == i32_const(34) {
																goto l13
															}
															t116 := v1
															if t116 != i32_const(47) {
																goto l0
															}
															t118 := v2
															binary.LittleEndian.PutUint64(m.Memory[uint32(t118+84):], uint64(v14))
															t121 := m._sql3lexer_peek(v0)
															if t121 != i32_const(19) {
																goto l14
															}
															t123 := v5
															t124 := t123 + i32_const(8)
															m._sql3parse_expression(t124, v0)
															t126 := v2
															binary.LittleEndian.PutUint64(m.Memory[uint32(t126+92):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v5+8):]))))
															goto l15
														}
													l6:
														;
														t129 := v2
														binary.LittleEndian.PutUint64(m.Memory[uint32(t129+36):], uint64(v14))
														t132 := m._sql3lexer_next(v0)
														if t132 != i32_const(23) {
															goto l0
														}
														t134 := v2
														m.Memory[uint32(t134+32)] = byte(i32_const(1))
														t135 := v0
														m._sql3parse_optionalorder(t135, v6)
														t137 := v0
														t139 := m._sql3parse_optionalconflitclause(t137, v13)
														if t139 != 0 {
															goto l0
														}
														t141 := m._sql3lexer_peek(v0)
														if t141 != i32_const(37) {
															goto l15
														}
														t144 := m._sql3lexer_next(v0)
														_ = t144
														t145 := v2
														m.Memory[uint32(t145+33)] = byte(i32_const(1))
														goto l15
													}
												l12:
													;
													t146 := v2
													binary.LittleEndian.PutUint64(m.Memory[uint32(t146+52):], uint64(v14))
													t149 := m._sql3lexer_next(v0)
													if t149 != i32_const(46) {
														goto l0
													}
													t151 := v2
													m.Memory[uint32(t151+34)] = byte(i32_const(1))
													t152 := v0
													t154 := m._sql3parse_optionalconflitclause(t152, v11)
													if t154 == 0 {
														goto l15
													}
													goto l0
												}
											l8:
												;
												t156 := v2
												t158 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v2+76):]))
												t159 := t158 + i32_const(1)
												v1 = t159
												binary.LittleEndian.PutUint32(m.Memory[uint32(t156+76):], uint32(t159))
												t161 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v2+80):]))
												t162 := v1
												t164 := m._realloc(t161, i32_shl(t162, i32_const(4)))
												v1 = t164
												if t164 == 0 {
													goto l0
												}
												t166 := v2
												binary.LittleEndian.PutUint32(m.Memory[uint32(t166+80):], uint32(v1))
												t168 := v1
												t170 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v2+76):]))
												t172 := t168 + i32_shl(t170, i32_const(4))
												v1 = t172
												t173 := t172 - i32_const(16)
												binary.LittleEndian.PutUint64(m.Memory[uint32(t173):], uint64(v14))
												t175 := v5
												t176 := t175 + i32_const(8)
												m._sql3parse_expression(t176, v0)
												t178 := v1
												t179 := t178 - i32_const(8)
												binary.LittleEndian.PutUint64(m.Memory[uint32(t179):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v5+8):]))))
												goto l15
											}
										l14:
											;
											m._sql3lexer_checkskip(v0)
											v7 = int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0):]))
											t186 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+8):]))
											v8 = t186
											v1 = t186
											t188 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+4):]))
											v9 = t188
											if uint32(t188) > uint32(v8) {
												t191 := v0
												t192 := v8
												t193 := t192 + i32_const(1)
												v1 = t193
												binary.LittleEndian.PutUint32(m.Memory[uint32(t191+8):], uint32(t193))
												t194 := v7
												t197 := int32(m.Memory[uint32(t194+v8)])
												v10 = t197
												var t198 int32
												if t197 == i32_const(39) {
													t198 = 1
												}
												t199 := v10
												var t200 int32
												if t199 == i32_const(34) {
													t200 = 1
												}
												t201 := t198 | t200
												if t201 != 0 {
													goto l16
												}
											}
											t202 := v1
											t203 := v9
											t204 := v1
											t207 := t203
											if uint32(t204) > uint32(v9) {
												t207 = t202
											}
											v3 = t207
										l20:
											{
												t208 := v1
												if t208 == v3 {
													v1 = v3
													goto l17
												}
												t212 := v1
												t215 := int32(m.Memory[uint32(t212+v7)])
												v4 = t215
												var t216 int32
												if t215 == 0 {
													t216 = 1
												}
												t218 := m._symbol_is_toskip(v4)
												t219 := t216 | t218
												t220 := v4
												var t221 int32
												if t220 == i32_const(10) {
													t221 = 1
												}
												t222 := v4
												var t223 int32
												if t222 == i32_const(13) {
													t223 = 1
												}
												t225 := t219 | (t221 | t223)
												if t225 != 0 {
													goto l17
												}
												{
													{
														t226 := v4
														switch t226 - i32_const(41) {
														default:
															goto l18
														case 0:
															goto l17
														case 1:
															goto l19
														case 2:
															goto l19
														case 3:
															goto l17
														}
													}
												l18:
													;
													t228 := v4
													if t228 == i32_const(59) {
														goto l17
													}
												}
											l19:
												;
												t230 := v0
												t231 := v1
												t232 := t231 + i32_const(1)
												v1 = t232
												binary.LittleEndian.PutUint32(m.Memory[uint32(t230+8):], uint32(t232))
												goto l20
											}
										}
									l13:
										;
										t233 := v2
										binary.LittleEndian.PutUint64(m.Memory[uint32(t233+100):], uint64(v14))
										t236 := m._sql3lexer_next(v0)
										if t236 != i32_const(2) {
											goto l0
										}
										t238 := v2
										binary.LittleEndian.PutUint64(m.Memory[uint32(t238+108):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v0+12):]))))
										goto l15
									}
								l11:
									;
									t241 := v2
									binary.LittleEndian.PutUint64(m.Memory[uint32(t241+116):], uint64(v14))
									t244 := m._sql3parse_foreignkey_clause(v0)
									v1 = t244
									if t244 == 0 {
										goto l0
									}
									t246 := v2
									binary.LittleEndian.PutUint32(m.Memory[uint32(t246+124):], uint32(v1))
									goto l15
								}
							l10:
								;
								t248 := v2
								binary.LittleEndian.PutUint64(m.Memory[uint32(t248+128):], uint64(v14))
								t250 := v1
								if t250 == i32_const(38) {
									t253 := m._sql3lexer_next(v0)
									v1 = t253
									var t255 int32
									if t253 == i32_const(39) {
										t257 := m._sql3lexer_next(v0)
										t255 = t257
									} else {
										t258 := v1
										t255 = t258
									}
									if t255 != i32_const(15) {
										goto l0
									}
								}
								t261 := m._sql3lexer_peek(v0)
								if t261 != i32_const(19) {
									goto l0
								}
								t263 := v5
								t264 := t263 + i32_const(8)
								m._sql3parse_expression(t264, v0)
								t266 := v2
								binary.LittleEndian.PutUint64(m.Memory[uint32(t266+136):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v5+8):]))))
								t270 := m._sql3lexer_peek(v0)
								v1 = t270
								t271 := v2
								binary.LittleEndian.PutUint32(m.Memory[uint32(t271+144):], uint32(i32_const(0)))
								t272 := v1
								t273 := t272 & i32_const(62)
								if t273 != i32_const(40) {
									goto l15
								}
								t276 := m._sql3lexer_next(v0)
								_ = t276
								t277 := v2
								t278 := v1
								t280 := i32_const(2)
								if t278 == i32_const(40) {
									t280 = i32_const(1)
								}
								binary.LittleEndian.PutUint32(m.Memory[uint32(t277+144):], uint32(t280))
								goto l15
							}
						l7:
							;
							t281 := v2
							m.Memory[uint32(t281+35)] = byte(i32_const(1))
							t282 := v2
							binary.LittleEndian.PutUint64(m.Memory[uint32(t282+64):], uint64(v14))
							t284 := v0
							t286 := m._sql3parse_optionalconflitclause(t284, v12)
							if t286 == 0 {
								goto l15
							}
							goto l0
						}
					l16:
						;
					l22:
						{
							{
								t288 := v9
								t289 := v1
								v3 = t289
								if uint32(t288) <= uint32(t289) {
									goto l21
								}
								t291 := v0
								t292 := v1
								t293 := t292 + i32_const(1)
								v1 = t293
								binary.LittleEndian.PutUint32(m.Memory[uint32(t291+8):], uint32(t293))
								t294 := v3
								t297 := int32(m.Memory[uint32(t294+v7)])
								v4 = t297
								if t297 == 0 {
									goto l21
								}
								t299 := v4
								if t299 != v10 {
									goto l22
								}
								t302 := v1
								if uint32(t302) >= uint32(v9) {
									goto l17
								}
								t305 := v10
								t306 := v1
								if t305 != int32(m.Memory[uint32(t306+v7)]) {
									goto l17
								}
								t311 := v0
								t312 := v3
								t313 := t312 + i32_const(2)
								v1 = t313
								binary.LittleEndian.PutUint32(m.Memory[uint32(t311+8):], uint32(t313))
								goto l22
							}
						l21:
						}
						v3 = i32_const(0)
						t314 := v10
						t105 = i32_const(0)
						if t314 != 0 {
							goto l23
						}
						_ = i32_const(0)
					}
				l17:
					;
					t315 := v7
					v3 = t315 + v8
					t318 := v1
					t320 := t318 - v8
					t105 = t320
				}
			l23:
				;
				binary.LittleEndian.PutUint32(m.Memory[uint32(t104+96):], uint32(t105))
				t321 := v2
				binary.LittleEndian.PutUint32(m.Memory[uint32(t321+92):], uint32(v3))
				goto l15
			}
		}
	l4:
		;
		v3 = v2
	}
l0:
	;
	t324 := v5
	m.___stack_pointer = t324 + i32_const(16)
	t326 := v3
	return t326
}
func (m Module) _realloc(v0 int32, v1 int32) int32 {
	var v2, v3 int32
	_, _ = v2, v3
	if v0 == 0 {
		t3 := m._malloc(v1)
		return t3
	}
	t4 := v1
	if uint32(t4) < uint32(i32_const(17)) {
		t6 := v0
		return t6
	}
	t7 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(i32_const(65952)):]))
	t9 := m._malloc(v1)
	v3 = t9
	t11 := t7 - v0
	v2 = t11
	t12 := v1
	t13 := v1
	t16 := t12
	if uint32(t13) > uint32(v2) {
		t16 = t11
	}
	v1 = t16
	if t16 != 0 {
		t17 := v3
		t18 := v0
		memory_copy(m.Memory, v1, t18, t17)
	}
	t20 := v3
	return t20
}
func (m Module) _sql3parse_expression(v0 int32, v1 int32) {
	var v2, v3, v4, v5, v6, v7, v8, v9, v10 int32
	_, _, _, _, _, _, _, _, _ = v2, v3, v4, v5, v6, v7, v8, v9, v10
	m._sql3lexer_checkskip(v1)
	{
		{
			t2 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v1+8):]))
			v6 = t2
			t4 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v1+4):]))
			v7 = t4
			if uint32(t2) >= uint32(t4) {
				goto l0
			}
			t6 := v1
			t7 := v6
			t8 := t7 + i32_const(1)
			v2 = t8
			binary.LittleEndian.PutUint32(m.Memory[uint32(t6+8):], uint32(t8))
			t10 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v1):]))
			v8 = t10
			t12 := t10 + v6
			v9 = t12
			t13 := int32(m.Memory[uint32(t12)])
			if t13 != i32_const(40) {
				goto l0
			}
			v5 = i32_const(1)
			goto l1
		}
	l0:
		;
		t15 := v0
		binary.LittleEndian.PutUint64(m.Memory[uint32(t15):], uint64(i64_const(0)))
		return
	}
l1:
	;
l5:
	{
		{
			t16 := v2
			if uint32(t16) >= uint32(v7) {
				v3 = v2
				goto l2
			}
			t20 := v1
			t21 := v2
			t22 := t21 + i32_const(1)
			v3 = t22
			binary.LittleEndian.PutUint32(m.Memory[uint32(t20+8):], uint32(t22))
			t23 := v2
			v4 = t23 + v8
			v2 = v3
			{
				{
					{
						{
							t28 := int32(m.Memory[uint32(v4)])
							v4 = t28
							switch t28 - i32_const(34) {
							default:
								goto l3
							case 0:
								goto l4
							case 1:
								goto l5
							case 2:
								goto l5
							case 3:
								goto l5
							case 4:
								goto l5
							case 5:
								goto l4
							case 6:
								goto l6
							case 7:
								goto l7
							}
						}
					l3:
						;
						if v4 == 0 {
							goto l2
						}
						goto l5
					}
				l4:
					;
				l8:
					{
						t32 := v7
						t33 := v2
						v3 = t33
						if uint32(t32) <= uint32(t33) {
							goto l5
						}
						t35 := v1
						t36 := v2
						t37 := t36 + i32_const(1)
						v2 = t37
						binary.LittleEndian.PutUint32(m.Memory[uint32(t35+8):], uint32(t37))
						t38 := v3
						t41 := int32(m.Memory[uint32(t38+v8)])
						v10 = t41
						if t41 == 0 {
							goto l5
						}
						t43 := v4
						if t43 != v10 {
							goto l8
						}
						t46 := v2
						if uint32(t46) >= uint32(v7) {
							goto l5
						}
						t49 := v2
						t52 := int32(m.Memory[uint32(t49+v8)])
						if t52 != v4 {
							goto l5
						}
						t55 := v1
						t56 := v3
						t57 := t56 + i32_const(2)
						v2 = t57
						binary.LittleEndian.PutUint32(m.Memory[uint32(t55+8):], uint32(t57))
						goto l8
					}
				}
			l6:
				;
				t58 := v5
				v5 = t58 + i32_const(1)
				goto l5
			}
		l7:
			;
			t60 := v5
			t61 := t60 - i32_const(1)
			v5 = t61
			if t61 != 0 {
				goto l5
			}
		}
	l2:
	}
	t62 := v0
	binary.LittleEndian.PutUint32(m.Memory[uint32(t62):], uint32(v9))
	t64 := v0
	t65 := v3
	binary.LittleEndian.PutUint32(m.Memory[uint32(t64+4):], uint32(t65-v6))
}
func (m Module) _sql3parse_optionalorder(v0 int32, v1 int32) {
	var v2 int32
	_ = v2
	t1 := m._sql3lexer_peek(v0)
	v2 = t1
	t2 := v1
	binary.LittleEndian.PutUint32(m.Memory[uint32(t2):], uint32(i32_const(0)))
	t3 := v2
	t4 := t3 - i32_const(35)
	if uint32(t4) <= uint32(i32_const(1)) {
		t7 := m._sql3lexer_next(v0)
		_ = t7
		t8 := v1
		t9 := v2
		t11 := i32_const(2)
		if t9 == i32_const(35) {
			t11 = i32_const(1)
		}
		binary.LittleEndian.PutUint32(m.Memory[uint32(t8):], uint32(t11))
	}
}
func (m Module) _sql3parse_optionalconflitclause(v0 int32, v1 int32) int32 {
	var v2, v3 int32
	_, _ = v2, v3
	t1 := m._sql3lexer_peek(v0)
	v3 = t1
	t2 := v1
	binary.LittleEndian.PutUint32(m.Memory[uint32(t2):], uint32(i32_const(0)))
	{
		t3 := v3
		if t3 != i32_const(27) {
			goto l0
		}
		t6 := m._sql3lexer_next(v0)
		_ = t6
		v2 = i32_const(2)
		t8 := m._sql3lexer_next(v0)
		if t8 != i32_const(28) {
			goto l0
		}
		t11 := m._sql3lexer_next(v0)
		v0 = t11
		t12 := t11 - i32_const(29)
		if uint32(t12) > uint32(i32_const(4)) {
			goto l0
		}
		t14 := v1
		t15 := v0
		binary.LittleEndian.PutUint32(m.Memory[uint32(t14):], uint32(t15-i32_const(28)))
		v2 = i32_const(0)
	}
l0:
	;
	t17 := v2
	return t17
}
func (m Module) _sql3parse_foreignkey_clause(v0 int32) int32 {
	var v1, v2, v3 int32
	_, _, _ = v1, v2, v3
	{
		t0 := m._malloc(i32_const(36))
		v1 = t0
		if t0 == 0 {
			goto l0
		}
		t3 := m._sql3lexer_next(v0)
		if t3 != i32_const(2) {
			goto l0
		}
		t5 := v1
		binary.LittleEndian.PutUint64(m.Memory[uint32(t5):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v0+12):]))))
		t9 := m._sql3lexer_peek(v0)
		if t9 == i32_const(19) {
			t12 := m._sql3lexer_next(v0)
			_ = t12
		l1:
			{
				t14 := m._sql3lexer_next(v0)
				if t14 != i32_const(2) {
					goto l0
				}
				t16 := v1
				t18 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v1+8):]))
				t19 := t18 + i32_const(1)
				v2 = t19
				binary.LittleEndian.PutUint32(m.Memory[uint32(t16+8):], uint32(t19))
				t21 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v1+12):]))
				t22 := v2
				t23 := i32_shl(t22, i32_const(3))
				v3 = t23
				t24 := m._realloc(t21, t23)
				v2 = t24
				if t24 == 0 {
					goto l0
				}
				t26 := v1
				binary.LittleEndian.PutUint32(m.Memory[uint32(t26+12):], uint32(v2))
				t28 := v2
				t30 := t28 + v3
				t31 := t30 - i32_const(8)
				binary.LittleEndian.PutUint64(m.Memory[uint32(t31):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v0+12):]))))
				t35 := m._sql3lexer_peek(v0)
				t37 := m._sql3lexer_next(v0)
				v3 = t37
				if t35 == i32_const(18) {
					goto l1
				}
			}
			t39 := v3
			if t39 != i32_const(20) {
				goto l0
			}
		}
	l3:
		{
			t42 := m._sql3lexer_peek(v0)
			v2 = t42
			t43 := t42 - i32_const(27)
			v3 = t43
			var t44 int32
			if uint32(t43) <= uint32(i32_const(26)) {
				t44 = 1
			}
			t46 := i32_shl(i32_const(1), v3)
			t47 := t46 & i32_const(100663297)
			t48 := i32_const(0)
			if t47 != 0 {
				t48 = t44
			}
			t49 := v2
			var t50 int32
			if t49 == i32_const(10) {
				t50 = 1
			}
			if t48|t50 == 0 {
				t53 := v1
				return t53
			}
			t55 := m._sql3lexer_next(v0)
			_ = t55
			var t56 int32
			{
				t57 := v2
				if t57 != i32_const(10) {
					t59 := v2
					if t59 != i32_const(27) {
						t61 := v2
						t56 = i32_const(0)
						if t61 != i32_const(52) {
							goto l2
						}
						_ = i32_const(0)
						t64 := m._sql3lexer_next(v0)
						if t64 != i32_const(2) {
							goto l0
						}
						t66 := v1
						binary.LittleEndian.PutUint64(m.Memory[uint32(t66+24):], uint64(int64(binary.LittleEndian.Uint64(m.Memory[uint32(v0+12):]))))
						goto l3
					}
					t70 := m._sql3lexer_next(v0)
					v2 = t70
					t71 := t70 - i32_const(45)
					if uint32(t71) < uint32(i32_const(-2)) {
						goto l0
					}
					{
						{
							{
								{
									t74 := m._sql3lexer_next(v0)
									switch t74 - i32_const(45) {
									default:
										goto l3
									case 0:
										goto l4
									case 1:
										goto l3
									case 2:
										goto l3
									case 3:
										goto l5
									case 4:
										goto l6
									case 5:
										goto l7
									}
								}
							l5:
								;
								t76 := v2
								if t76 == i32_const(44) {
									t78 := v1
									binary.LittleEndian.PutUint32(m.Memory[uint32(t78+20):], uint32(i32_const(3)))
									goto l3
								}
								t79 := v1
								binary.LittleEndian.PutUint32(m.Memory[uint32(t79+16):], uint32(i32_const(3)))
								goto l3
							}
						l6:
							;
							t80 := v2
							if t80 == i32_const(44) {
								t82 := v1
								binary.LittleEndian.PutUint32(m.Memory[uint32(t82+20):], uint32(i32_const(4)))
								goto l3
							}
							t83 := v1
							binary.LittleEndian.PutUint32(m.Memory[uint32(t83+16):], uint32(i32_const(4)))
							goto l3
						}
					l4:
						;
						t85 := m._sql3lexer_next(v0)
						v3 = t85
						t86 := t85 - i32_const(48)
						if uint32(t86) < uint32(i32_const(-2)) {
							goto l0
						}
						t88 := v3
						if t88 == i32_const(46) {
							t90 := v2
							if t90 == i32_const(44) {
								t92 := v1
								binary.LittleEndian.PutUint32(m.Memory[uint32(t92+20):], uint32(i32_const(1)))
								goto l3
							}
							t93 := v1
							binary.LittleEndian.PutUint32(m.Memory[uint32(t93+16):], uint32(i32_const(1)))
							goto l3
						}
						t94 := v2
						if t94 == i32_const(44) {
							t96 := v1
							binary.LittleEndian.PutUint32(m.Memory[uint32(t96+20):], uint32(i32_const(2)))
							goto l3
						}
						t97 := v1
						binary.LittleEndian.PutUint32(m.Memory[uint32(t97+16):], uint32(i32_const(2)))
						goto l3
					}
				l7:
					;
					t99 := m._sql3lexer_next(v0)
					if t99 != i32_const(51) {
						goto l0
					}
					t101 := v2
					if t101 == i32_const(44) {
						t103 := v1
						binary.LittleEndian.PutUint32(m.Memory[uint32(t103+20):], uint32(i32_const(5)))
						goto l3
					}
					t104 := v1
					binary.LittleEndian.PutUint32(m.Memory[uint32(t104+16):], uint32(i32_const(5)))
					goto l3
				}
				t106 := m._sql3lexer_next(v0)
				v2 = t106
				t56 = i32_const(1)
			}
		l2:
			;
			v3 = t56
			t107 := v2
			if t107 != i32_const(53) {
				goto l0
			}
			t109 := v1
			t110 := v3
			t111 := i32_const(1)
			if t110 != 0 {
				t111 = i32_const(4)
			}
			binary.LittleEndian.PutUint32(m.Memory[uint32(t109+32):], uint32(t111))
			t113 := m._sql3lexer_peek(v0)
			if t113 != i32_const(54) {
				goto l3
			}
			t116 := m._sql3lexer_next(v0)
			_ = t116
			{
				{
					t118 := m._sql3lexer_next(v0)
					switch t118 - i32_const(55) {
					default:
						goto l0
					case 0:
						goto l8
					case 1:
						goto l9
					}
				}
			l8:
				;
				t120 := v1
				t121 := v3
				t122 := i32_const(2)
				if t121 != 0 {
					t122 = i32_const(5)
				}
				binary.LittleEndian.PutUint32(m.Memory[uint32(t120+32):], uint32(t122))
				goto l3
			}
		l9:
			;
			t123 := v1
			t124 := v3
			t125 := i32_const(3)
			if t124 != 0 {
				t125 = i32_const(6)
			}
			binary.LittleEndian.PutUint32(m.Memory[uint32(t123+32):], uint32(t125))
			goto l3
		}
	}
l0:
	;
	return i32_const(0)
}
func (m Module) _symbol_is_toskip(v0 int32) int32 {
	var v1, v2 int32
	_, _ = v1, v2
	v1 = i32_const(1)
	{
		t0 := v0
		t1 := t0 & i32_const(253)
		if t1 == i32_const(9) {
			goto l0
		}
		t3 := v0
		t4 := t3 & i32_const(255)
		v2 = t4
		var t5 int32
		if t4 == i32_const(12) {
			t5 = 1
		}
		t6 := v2
		var t7 int32
		if t6 == i32_const(32) {
			t7 = 1
		}
		t8 := t5 | t7
		if t8 != 0 {
			goto l0
		}
		t9 := v0
		var t10 int32
		if t9 == i32_const(10) {
			t10 = 1
		}
		t11 := v0
		var t12 int32
		if t11 == i32_const(13) {
			t12 = 1
		}
		v1 = t10 | t12
	}
l0:
	;
	t14 := v1
	return t14
}
func (m Module) _symbol_is_comment(v0 int32, v1 int32) int32 {
	var v2 int32
	_ = v2
	{
		{
			{
				{
					t0 := v0
					t1 := t0 & i32_const(255)
					switch t1 - i32_const(45) {
					default:
						goto l0
					case 0:
						goto l1
					case 1:
						goto l0
					case 2:
						goto l2
					}
				}
			l1:
				;
				v0 = i32_const(1)
				t4 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v1+8):]))
				t5 := t4 + i32_const(1)
				v2 = t5
				if uint32(t5) >= uint32(int32(binary.LittleEndian.Uint32(m.Memory[uint32(v1+4):]))) {
					goto l0
				}
				t10 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v1):]))
				t13 := int32(m.Memory[uint32(t10+v2)])
				if t13 != i32_const(45) {
					goto l0
				}
				goto l3
			}
		l2:
			;
			v0 = i32_const(1)
			t16 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v1+8):]))
			t17 := t16 + i32_const(1)
			v2 = t17
			if uint32(t17) >= uint32(int32(binary.LittleEndian.Uint32(m.Memory[uint32(v1+4):]))) {
				goto l0
			}
			t22 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v1):]))
			t25 := int32(m.Memory[uint32(t22+v2)])
			if t25 == i32_const(42) {
				goto l3
			}
		}
	l0:
		;
		v0 = i32_const(0)
	}
l3:
	;
	t27 := v0
	return t27
}
func (m Module) _sql3lexer_comment(v0 int32) {
	var v1, v2, v3, v4, v5, v6, v7, v8, v9, v10 int32
	_, _, _, _, _, _, _, _, _, _ = v1, v2, v3, v4, v5, v6, v7, v8, v9, v10
	v5 = int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0):]))
	var t2 int32
	{
		t4 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+8):]))
		v1 = t4
		t6 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+4):]))
		v6 = t6
		if uint32(t4) >= uint32(t6) {
			v2 = v1
			t2 = i32_const(0)
			goto l0
		}
		t9 := v0
		t10 := v1
		t11 := t10 + i32_const(1)
		v2 = t11
		binary.LittleEndian.PutUint32(m.Memory[uint32(t9+8):], uint32(t11))
		t12 := v1
		t15 := int32(m.Memory[uint32(t12+v5)])
		var t16 int32
		if t15 == i32_const(47) {
			t16 = 1
		}
		t2 = t16
	}
l0:
	;
	v7 = t2
	{
		t17 := v2
		if uint32(t17) >= uint32(v6) {
			v1 = v2
			goto l1
		}
		t21 := v0
		t22 := v2
		t23 := t22 + i32_const(1)
		v1 = t23
		binary.LittleEndian.PutUint32(m.Memory[uint32(t21+8):], uint32(t23))
		t24 := v2
		t27 := int32(m.Memory[uint32(t24+v5)])
		var t28 int32
		if t27 == i32_const(42) {
			t28 = 1
		}
		v3 = t28
	}
l1:
	;
	t29 := v1
	t30 := v6
	t31 := v1
	t34 := t30
	if uint32(t31) > uint32(v6) {
		t34 = t29
	}
	v4 = t34
	t35 := v3
	v8 = t35 & v7
	v9 = i32_const(1)
	v3 = v1
	{
		{
		l3:
			{
				t39 := v4
				t40 := v3
				v2 = t40
				if t39 == t40 {
					goto l2
				}
				t42 := v0
				t43 := v2
				t44 := t43 + i32_const(1)
				v3 = t44
				binary.LittleEndian.PutUint32(m.Memory[uint32(t42+8):], uint32(t44))
				t45 := v2
				t47 := t45 + v5
				v7 = t47
				t48 := int32(m.Memory[uint32(t47)])
				v10 = t48
				if t48 == 0 {
					v4 = v3
					goto l2
				}
				t51 := v8
				if t51 != 0 {
					t52 := v10
					var t53 int32
					if t52 != i32_const(42) {
						t53 = 1
					}
					t54 := v3
					var t56 int32
					if uint32(t54) >= uint32(v6) {
						t56 = 1
					}
					t57 := t53 | t56
					if t57 != 0 {
						goto l3
					}
					t58 := v7
					t60 := int32(m.Memory[uint32(t58+i32_const(1))])
					if t60 != i32_const(47) {
						goto l3
					}
					t62 := v0
					t63 := v2
					t64 := t63 + i32_const(2)
					v4 = t64
					binary.LittleEndian.PutUint32(m.Memory[uint32(t62+8):], uint32(t64))
					goto l4
				}
				{
					t65 := v10
					switch t65 - i32_const(10) {
					default:
						goto l3
					case 0:
						goto l5
					case 1:
						goto l3
					case 2:
						goto l3
					case 3:
						goto l5
					}
				}
			l5:
			}
			t67 := v2
			v4 = t67 + i32_const(1)
		}
	l4:
		;
		v9 = i32_const(0)
	}
l2:
	;
	t70 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+20):]))
	v0 = t70
	if t70 != 0 {
		t71 := v0
		t72 := v1
		binary.LittleEndian.PutUint32(m.Memory[uint32(t71):], uint32(t72+v5))
		t75 := v0
		t76 := v8
		t77 := i32_const(-1)
		if t76 != 0 {
			t77 = i32_const(-2)
		}
		t78 := v9
		t79 := t77
		if t78 != 0 {
			t79 = i32_const(0)
		}
		t81 := t79 - v1
		binary.LittleEndian.PutUint32(m.Memory[uint32(t75+4):], uint32(t81+v4))
	}
}
func (m Module) _str_nocasencmp(v0 int32, v1 int32, v2 int32) int32 {
	var v3, v4, v5, v6 int32
	_, _, _, _ = v3, v4, v5, v6
	{
	l1:
		{
			if v2 == 0 {
				goto l0
			}
			t3 := int32(m.Memory[uint32(v0)])
			v3 = t3
			t4 := m._tolower(t3)
			v4 = t4
			t7 := m._tolower(int32(m.Memory[uint32(v1)]))
			v5 = t7
			if t4 == t7 {
				if v3 == 0 {
					goto l0
				}
				t11 := v2
				v2 = t11 - i32_const(1)
				t13 := v1
				v1 = t13 + i32_const(1)
				t15 := v0
				v0 = t15 + i32_const(1)
				goto l1
			}
		}
		t17 := v4
		v6 = t17 - v5
	}
l0:
	;
	t20 := v6
	return t20
}
func (m Module) _token_is_column_constraint(v0 int32) int32 {
	t3 := int32(i64_shr_u(i64_const(145427649299456), int64(uint32(v0))))
	t4 := v0
	var t5 int32
	if uint32(t4) < uint32(i32_const(48)) {
		t5 = 1
	}
	t6 := t3 & t5
	return t6
}
func (m Module) _sql3lexer_checkskip(v0 int32) {
	var v1, v2 int32
	_, _ = v1, v2
l0:
	{
		v1 = i32_const(0)
		t1 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+8):]))
		v2 = t1
		if uint32(t1) < uint32(int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0+4):]))) {
			t6 := int32(binary.LittleEndian.Uint32(m.Memory[uint32(v0):]))
			v1 = int32(m.Memory[uint32(t6+v2)])
		}
		t11 := m._symbol_is_toskip(v1)
		if t11 != 0 {
			t12 := v0
			t13 := v2
			binary.LittleEndian.PutUint32(m.Memory[uint32(t12+8):], uint32(t13+i32_const(1)))
			goto l0
		}
		t15 := v1
		t17 := m._symbol_is_comment(t15, v0)
		if t17 != 0 {
			m._sql3lexer_comment(v0)
			goto l0
		}
	}
}

func i32_const(x int32) int32 { return x }

func i64_const(x int64) int64 { return x }

func i32_shl(x, y int32) int32 {
	return x << (y & 31)
}

func i32_shr_u(x, y int32) int32 {
	return int32(uint32(x) >> (y & 31))
}

func i64_shr_u(x, y int64) int64 {
	return int64(uint64(x) >> (y & 63))
}

func memory_grow(mem *[]byte, delta int32) int32 {
	oldLen := int32(len(*mem) >> 16)
	if delta == 0 {
		return oldLen
	}
	*mem = append(*mem, make([]byte, uint(delta)<<16)...)
	return oldLen
}

func memory_copy(mem []byte, n, src, dest int32) {
	x := uint(uint32(dest))
	z := uint(uint32(src))
	y := x + uint(uint32(n))
	w := z + uint(uint32(n))
	copy(mem[x:y], mem[z:w])
}

const (
	data0 = "temporary\x00primary\x00initially\x00key\x00without\x00abort\x00not\x00constraint\x00autoincrement\x00default\x00set\x00restrict\x00conflict\x00always\x00exists\x00references\x00as\x00alter\x00drop\x00temp\x00to\x00no\x00action\x00column\x00foreign\x00null\x00fail\x00virtual\x00check\x00rollback\x00match\x00if\x00unique\x00delete\x00collate\x00immediate\x00create\x00update\x00ignore\x00rename\x00table\x00deferrable\x00cascade\x00replace\x00rowid\x00generated\x00deferred\x00stored\x00add\x00desc\x00asc\x00\x00\x00\x00\x90\x00\x01\x00\x04\x00\x00\x00\x15\x00\x00\x00\x16\x00\x00\x00\x00\x00\x00\x00\x18\x00\x00\x00\x19\x00\x00\x00\x1a\x00\x00\x00\x16\x00\x00\x00\x00\x00\x00\x00\x18\x00\x00\x00\x19\x00\x00\x00\x1a"
	data1 = "\x02\x00\xb0\x01\x01"
)
