name: Test

on:
  push:
    branches: [ 'main' ]
    paths:
      - '**.go'
      - '**.mod'
      - '**.wasm'
      - '**.yml'
  pull_request:
    branches: [ 'main' ]
    paths:
      - '**.go'
      - '**.mod'
      - '**.wasm'
      - '**.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-go@v7
      with: { go-version: stable }

    - name: Format
      run: gofmt -s -w . && git diff --exit-code
      if: matrix.os != 'windows-latest'

    - name: Tidy
      run: go mod tidy && git diff --exit-code

    - name: Download
      run: go mod download

    - name: Verify
      run: go mod verify

    - name: Vet
      run: go vet ./...

    - name: Build
      run: go build ./...

    - name: Test
      run: go test ./... -bench . -benchtime=1x

    - name: Test BSD locks
      run: go test -tags sqlite3_flock ./...
      if: matrix.os != 'windows-latest'

    - name: Test dot locks
      run: go test -tags sqlite3_dotlk ./...
      if: matrix.os != 'windows-latest'

    - name: Test modules
      shell: bash
      run: |
        go work init .
        go work use -r gormlite
        go test ./gormlite

    - name: Test GORM
      shell: bash
      run: gormlite/test.sh
      if: matrix.os == 'ubuntu-latest'

    - name: Collect coverage
      run: |
        go get -tool github.com/dave/courtney@v0.4.4
        go tool courtney
      if: |
        github.event_name == 'push' &&
        matrix.os == 'ubuntu-latest'

    - uses: ncruces/go-coverage-report@v0
      with:
        coverage-file: coverage.out
        chart: true
        amend: true
      if: |
        github.event_name == 'push' &&
        matrix.os == 'ubuntu-latest'
